### ISSUE TITLE
SAS Exporter - 2 Issues: Exhibits infinite growth; Crashes R;

### ISSUE THREAD

**Issue by michaelwhammer** [tidyverse/haven#234]
There are several data sets that I work with that I am unable to export using haven. The R session either crashes or the export never finishes (and the size of exported file continues to grow into the GB/TB realm even when the data is relatively small).

Unable to export to SAS:
https://app.box.com/s/s2manpitopcyq2f0bj0fwi75ghqc0cgb
https://app.box.com/s/ev8rxwsg2j1413d7n48wu0xkeyjfnetf
https://app.box.com/s/nq552xwxde60n3q4hofob3am511h6i8d

Unable to export to SPSS:
https://app.box.com/s/qd2cggi588udrpkpdkk6v4axvtjl23ch

I am using:
haven_1.0.0
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

**Comment by michaelwhammer** [comment]
Updated issues to contain links to files.

**Comment by g3o2** [comment]
Looks likes this issue may be related to #235. 

Then, it also appears that the export experience may be different for different users. In my case, `write_sav` wrote a file. So, could it be that this were data set related ? Or could there be an R compatibility issue ?

**Comment by hadley** [comment]
Can you please provide an inline minimal reproducible example?

**Comment by mwh3780** [comment]
Download the 4 files from above to C:/TEMP/

```
library(haven)
load("C:/TEMP/sas_df1.Rdata")
haven::write_sas(sas_df1, "C:/TEMP/sas_df1.sas7bdat")
# > haven::write_sas(sas_df1, "C:/TEMP/sas_df1.sas7bdat")
# Error in write_sas_(data, normalizePath(path, mustWork = FALSE)) : 
#   Writing failure: Unable to write data.

# File becomes so large it fills my C drive (see screenshots below)
# This same error occurs for "C:/TEMP/sas_df3.Rdata" and "C:/TEMP/spss_df1.Rdata". Not included screenshots or code for brevity as it is identical.
```

![sasdf1](https://cloud.githubusercontent.com/assets/19755074/22257481/712821a0-e21b-11e6-8556-b3a0be3e1765.PNG)

![sasdf3](https://cloud.githubusercontent.com/assets/19755074/22257485/777bac16-e21b-11e6-98d8-f09c3e0b2016.PNG)

![spss_df1](https://cloud.githubusercontent.com/assets/19755074/22257488/798922c2-e21b-11e6-8c10-db63f036f243.PNG)

The following file crashes my R session
```
library(haven)
load("C:/TEMP/sas_df2.Rdata")
haven::write_sas(sas_df2, "C:/TEMP/sas_df2.sas7bdat")

# Crashes R: R Session Aborted screen
```
![r session aborted screen](https://cloud.githubusercontent.com/assets/19755074/22257491/7bd2891a-e21b-11e6-9077-831208377050.PNG)


I have down-sampled the files to be as small as possible while still producing the errors. I do not know which elements of the data are causing the issue.

**Comment by hadley** [comment]
It would helpful if you could make the example fully reproducible by using `download.file` to download to `tempdir()`.  No need to include screenshots

**Comment by evanmiller** [comment]
@michaelwhammer Please file separate issues for the SPSS and SAS exporters.

If the SPSS export exhibits infinite growth (but no crash) it is likely a duplicate of #245.

**Comment by michaelwhammer** [comment]
@evanmiller Yes, it appears that one of the issues I've experienced is the same as [#245](https://github.com/tidyverse/haven/issues/245) (exhibits infinite growth without crashing). As that issues seems to have been addressed I've changed the name of this issue to address the SAS exporter.

@hadley Fully reproducible code provided below.

I've provided files where the SAS exporter experiences issues:
- exhibits infinite growth (2 files provided);
- crashes R (1 file provided);

```
library(haven)

tmpdir <- tempdir()
filename <- "all_files.zip"
download.file("https://www.dropbox.com/s/gxik3b08tmyh3bu/all_files.zip?dl=1", filename, mode = "wb")
unzip(filename, exdir = tmpdir)
load(paste0(tmpdir, "\\all_files.Rdata"))

# sas_df1 - Gets stuck in loop
haven::write_sas(sas_df1,  paste0(tmpdir,"\\sas_df1.sas7bdat"))

# sas_df2 - Crashes R
haven::write_sas(sas_df2,  paste0(tmpdir,"\\sas_df2.sas7bdat"))

# sas_df3 - Gets stuck in loop
haven::write_sas(sas_df3,  paste0(tmpdir,"\\sas_df3.sas7bdat"))

> sessionInfo()  
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
  [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
  [1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
  [1] haven_1.0.0

loaded via a namespace (and not attached):
  [1] assertthat_0.1 tools_3.3.2    tibble_1.2     Rcpp_0.12.8
```

**Comment by hadley** [comment]
(Please don't include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away. I've deleted it from your issue to avoid cluttering up the discussion)

**Comment by hadley** [comment]
Slightly cleaned up reprex below. 

@evanmiller I still see both issues on latest haven.

```R
library(haven)

zip_path <- tempfile()
download.file("https://www.dropbox.com/s/gxik3b08tmyh3bu/all_files.zip?dl=1", zip_path)
rdata_path <- unzip(zip_path, exdir = basename(zip_path))
(load(rdata_path))

# sas_df1 - Gets stuck in loop
haven::write_sas(sas_df1, tempfile())

# sas_df2 - Crashes R
haven::write_sas(sas_df2, tempfile())

# sas_df3 - Gets stuck in loop
haven::write_sas(sas_df3,  tempfile())
```

I've cleaned up the issue title/comment thread to focus on key components of problem. Thanks for the correspondence so far :smile:

**Comment by evanmiller** [comment]
`sas_df2` is a divide-by-zero crash:

```
Exception Type:        EXC_ARITHMETIC (SIGFPE)
Exception Codes:       EXC_I386_DIV (divide by zero)
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Floating point exception: 8
Termination Reason:    Namespace SIGNAL, Code 0x8
Terminating Process:   exc handler [0]

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   haven.so                      	0x00000001100218ab sas7bdat_emit_header_and_meta_pages + 315
1   haven.so                      	0x00000001100215e4 sas7bdat_begin_data + 2292
2   haven.so                      	0x000000011001be55 readstat_begin_row + 165
3   haven.so                      	0x0000000110044645 Writer::write() + 1269
4   haven.so                      	0x0000000110044dd6 write_sas_(Rcpp::Vector<19, Rcpp::PreserveStorage>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 70
5   haven.so                      	0x0000000110049c2f haven_write_sas_ + 175
```

All issues appear to be related to rows not fitting into the default (and, currently, only possible) page size of 4096 bytes. Per #270 it looks like rows longer than 2048 bytes cause a hang, and rows longer than 4096 bytes cause a crash.

**Comment by evanmiller** [comment]
@hadley Should be "fixed" (return error instead of crash/hang) by https://github.com/WizardMac/ReadStat/commit/7d9d58097a23575bb9bfbed5286454080f2f6977
