### ISSUE TITLE
read_spss Unable to allocate memory.

### ISSUE THREAD

**Issue by aftollefsen** [tidyverse/haven#361]
Recently encountered this problem. I have updated packages. 

The code used to run without a hitch, but not anymore. Any suggestions would be very helpful. I have installed several packages lately, such as rmarkdown and pander, but they are not loaded in this session.

Data file can be downloaded from here: http://www.afrobarometer.org/data/merged-round-2-data-16-countries-2004 (might require login)

```
library(haven)
afro2 <- read_spss("merged_r2_data.sav")
Error in df_parse_sav_file(spec, user_na) : 
  Failed to parse merged_r2_data.sav: Unable to allocate memory.
```

**Comment by hadley** [comment]
This should be fixed in the development version.

**Comment by ytmytm** [comment]
I'm having similar issue with development version too:
```
> library(haven)
> data <- read_spss(file="c:/tmp/testdata.sav")
Error in df_parse_sav_file(spec, encoding, user_na) : 
  Failed to parse c:/tmp/testdata.sav: Unable to allocate memory.
```

R session info:
```
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Polish_Poland.1250  LC_CTYPE=Polish_Poland.1250    LC_MONETARY=Polish_Poland.1250
[4] LC_NUMERIC=C                   LC_TIME=Polish_Poland.1250    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] haven_1.1.1.9000

loaded via a namespace (and not attached):
 [1] readr_1.1.1     compiler_3.4.3  R6_2.2.2        magrittr_1.5    hms_0.4.1       tools_3.4.3    
 [7] pillar_1.2.0    tibble_1.4.2    yaml_2.1.16     Rcpp_0.12.15    forcats_0.3.0   pkgconfig_2.0.1
[13] rlang_0.2.0 
```

Dataset attached, just one row is enough to trigger it the error. I see the same behavior also if I recode all numerical data to missing and drop string variables.

[testdata.zip](https://github.com/tidyverse/haven/files/1785692/testdata.zip)

**Comment by hadley** [comment]
@ytmytm when did you install haven? We made some fixes in the last couple of weeks.

(Please don't include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away. I've deleted it from your issue to avoid cluttering up the discussion)

**Comment by aftollefsen** [comment]
Installed development version. Same code generated following error:
Error in .Call(`_haven_df_parse_sav_file`, spec, encoding, user_na) : 
  Incorrect number of arguments (3), expecting 2 for '_haven_df_parse_sav_file'

**Comment by ytmytm** [comment]
@hadley I installed development version today. Following comments from #342 I tried downgrading to 1.1.0 and then the file from my attachment can be loaded. But I would really like to be able to load data from zsav files too :).

**Comment by hadley** [comment]
@aftollefsen I _think_ that means you need to restart R

@evanmiller if you have a minute, can you please take a look at testdata.zip above?

**Comment by evanmiller** [comment]
Fixed for now in https://github.com/WizardMac/ReadStat/commit/748f1c5b95191d3c25d30488687da4cba57729a6

**Comment by ytmytm** [comment]
I confirm that with readstat patched with WizardMac/ReadStat@748f1c5 change I can load data from all problematic files.

You guys are great!

**Comment by ytmytm** [comment]
With readstat patched by WizardMac/ReadStat@748f1c5 I can load data from all problematic files except two.

For the attached examples (single row in each file) the problem persists.

[testdata2.zip](https://github.com/tidyverse/haven/files/1792732/testdata2.zip)

**Comment by evanmiller** [comment]
@ytmytm Thanks. These two files should now work with this commit: https://github.com/WizardMac/ReadStat/commit/88cbbda7105dce3847d57a2c5a32aabda33821bc

**Comment by ytmytm** [comment]
@evanmiller This solves all the problems I had. Thank you! You guys are awesome!

**Comment by gabriellimagomes15** [comment]
Hi everybody.

So I have installed have by devtools::install_github("hadley/haven", force=TRUE) but I am having same problem ` 'Error in .Call(`_haven_df_parse_sav_file`, spec, encoding, user_na) : 
  Incorrect number of arguments (3), expecting 2 for '_haven_df_parse_sav_file' `

Do I need do something more?

Thanks.

**Comment by hadley** [comment]
@gabriellimagomes15 if you are still having problem after installing the latest haven from github, please file a new issue including a reproducible example.
