### ISSUE TITLE
The file's timestamp string is invalid 

### ISSUE THREAD

**Issue by edvbb** [tidyverse/haven#488]
I try to read spss format
`df <- read_sav("https://www.hse.ru/data/2019/09/03/1539047667/r27iall_31.sav" )`
and get
```
Error in df_parse_sav_file(spec, encoding, user_na, cols_skip, n_max,  : 
  Failed to parse C:/Users/Администратор/AppData/Local/Temp/RtmpIRfOSh/filef401bbb26de: The file's timestamp string is invalid.
```

<details>
I changed encoding ````utf-8```` and ````cp1251```` but results are the same

When I before download the file to my local directory I have no mistake
`df <- read_sav("r27iall_31.sav") `

```
> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          6.2                         
year           2019                        
month          12                          
day            12                          
svn rev        77560                       
language       R                           
version.string R version 3.6.2 (2019-12-12)
nickname       Dark and Stormy Night  
```
</details>

**Comment by jnese** [comment]
I am having the same issue.

**Comment by mpaulacaldas** [comment]
I had the same issue with `read_dta()`. I get the impression that this is a problem with timestamps in other languages.

Here is an example from a Colombian survey. Note that `ago` is short for agosto (August in English).
``` r
library(haven)

download.file(
  "http://microdatos.dane.gov.co/index.php/catalog/641/download/12065/",
  "Abril.zip"
  )

unzip("Abril.zip")

abril <- read_dta("Abril.dta")
#> Invalid timestamp string (length=17): 20 ago 2019 10:00
#> Error in df_parse_dta_file(spec, encoding, cols_skip, n_max, skip, name_repair = .name_repair): Failed to parse /private/var/folders/kg/ppnll8_51mv64mtjwydqcmxr0000gn/T/RtmpWHnWrn/reprex52b54e525706/Abril.dta: The file's timestamp string is invalid.
```

<sup>Created on 2020-03-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.0 (2019-04-26)
#>  os       macOS  10.15.2              
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Europe/Paris                
#>  date     2020-03-12                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
#>  backports     1.1.5   2019-10-02 [1] CRAN (R 3.6.0)
#>  callr         3.4.2   2020-02-12 [1] CRAN (R 3.6.0)
#>  cli           2.0.1   2020-01-08 [1] CRAN (R 3.6.0)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.0)
#>  devtools      2.2.0   2019-09-07 [1] CRAN (R 3.6.0)
#>  digest        0.6.24  2020-02-12 [1] CRAN (R 3.6.0)
#>  DT            0.12    2020-02-05 [1] CRAN (R 3.6.0)
#>  ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.0)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 3.6.0)
#>  fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.0)
#>  forcats       0.4.0   2019-02-17 [1] CRAN (R 3.6.0)
#>  fs            1.3.1   2019-05-06 [1] CRAN (R 3.6.0)
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.0)
#>  haven       * 2.2.0   2019-11-08 [1] CRAN (R 3.6.0)
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.6.0)
#>  hms           0.5.3   2020-01-08 [1] CRAN (R 3.6.0)
#>  htmltools     0.4.0   2019-10-04 [1] CRAN (R 3.6.0)
#>  htmlwidgets   1.5.1   2019-10-08 [1] CRAN (R 3.6.0)
#>  knitr         1.28    2020-02-06 [1] CRAN (R 3.6.0)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.0)
#>  pillar        1.4.3   2019-12-20 [1] CRAN (R 3.6.0)
#>  pkgbuild      1.0.6   2019-10-09 [1] CRAN (R 3.6.0)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 3.6.0)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.0)
#>  prettyunits   1.1.1   2020-01-24 [1] CRAN (R 3.6.0)
#>  processx      3.4.2   2020-02-09 [1] CRAN (R 3.6.0)
#>  ps            1.3.2   2020-02-13 [1] CRAN (R 3.6.0)
#>  R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.0)
#>  Rcpp          1.0.3   2019-11-08 [1] CRAN (R 3.6.0)
#>  readr         1.3.1   2018-12-21 [1] CRAN (R 3.6.0)
#>  remotes       2.1.0   2019-06-24 [1] CRAN (R 3.6.0)
#>  rlang         0.4.4   2020-01-28 [1] CRAN (R 3.6.0)
#>  rmarkdown     2.1     2020-01-20 [1] CRAN (R 3.6.0)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.0)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
#>  stringi       1.4.6   2020-02-17 [1] CRAN (R 3.6.0)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.6.0)
#>  testthat      2.3.1   2019-12-01 [1] CRAN (R 3.6.0)
#>  tibble        2.1.3   2019-06-06 [1] CRAN (R 3.6.0)
#>  usethis       1.5.1   2019-07-04 [1] CRAN (R 3.6.0)
#>  vctrs         0.2.2   2020-01-24 [1] CRAN (R 3.6.0)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)
#>  xfun          0.12    2020-01-13 [1] CRAN (R 3.6.0)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 3.6.0)
#> 
#> [1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

</details>

**Comment by hadley** [comment]
@evanmiller is this a known issue? File at <http://microdatos.dane.gov.co/index.php/catalog/641/download/12065/Abril.zip>

**Comment by evanmiller** [comment]
@hadley this issue is fixed in ReadStat 1.1.2

https://github.com/WizardMac/ReadStat/commit/aed4ece6fefff6378543e5d7c0820bcd91561da4

Closing

**Comment by hadley** [comment]
Oops, should've re-run the reprex after I updated. Thanks for the fix!

**Comment by the-Zian** [comment]
I'm also experiencing this error. I cannot share the dataset as it is private. I tried re-installing `haven` but that hasn't resolved the error. Any suggestions?

**Comment by galalH** [comment]
> @evanmiller is this a known issue? File at http://microdatos.dane.gov.co/index.php/catalog/641/download/12065/Abril.zip

That file now works, but other files from the same microdata catalog still can't be parsed because of the date issue. See this one for example: http://microdatos.dane.gov.co/index.php/catalog/659/download/13776/Junio.zip (look for the Area - personas file).

**Comment by evanmiller** [comment]
@galalH Thanks. The linked file has a garbled timestamp. In the past ReadStat has returned an error on bad timestamps so as to encourage users to send in error reports, but this one is bad enough that I think it's time to lift the restriction.

Fixed in https://github.com/WizardMac/ReadStat/commit/b386f97c1c1d59b4956a6eb607fbae8509d3a1ac

**Comment by hmeleiro** [comment]
I'm still having this issue. I've searched and found this thread and [this one](https://github.com/tidyverse/haven/issues/216) but I don't get how to fix it. 

I'm having trouble with this sav file from a spanish research institute: https://analisis.cis.es/formulario.jsp?dwld=/Microdatos/MD3361.zip

```
Invalid date string (length=9): 11 040 22
Error: Failed to parse C:/Users/hmele/Documents/projects/contador/data/ICC/microdatos/mensuales/3361.sav: The file's timestamp string is invalid.
```

**Comment by jantleon** [comment]
> I'm still having this issue. I've searched and found this thread and [this one](https://github.com/tidyverse/haven/issues/216) but I don't get how to fix it.
> 
> I'm having trouble with this sav file from a spanish research institute: https://analisis.cis.es/formulario.jsp?dwld=/Microdatos/MD3361.zip
> 
> ```
> Invalid date string (length=9): 11 040 22
> Error: Failed to parse C:/Users/hmele/Documents/projects/contador/data/ICC/microdatos/mensuales/3361.sav: The file's timestamp string is invalid.
> ```

Hi, I'm having trouble also with CIS data, did you solve it?

**Comment by gorcha** [comment]
Hi @jantleon, there's an open issue at #683, please see there for updates.

Thanks!
